revise paths for darling erasure

diff --git a/mknix b/mknix
--- a/mknix
+++ b/mknix
@@ -1,7 +1,10 @@
 #!/usr/bin/env bash
 set -e
 
+# remote:
 url="github:bluesquall/tabula-rasa/sops-nix#encom"
+# local:
+url=".#encom"
 
 usage() {
   echo "please specify the drive to prepare for NixOS (e.g., /dev/nvme0n1)";
@@ -29,8 +32,13 @@ else
 fi
 
 echo "inspecting age private key at /tmp/key.txt"
-echo "sops-nix will use age public key $(age-keygen -y /tmp/key.txt)"
+pubkey=$(age-keygen -y /tmp/key.txt)
+if [[ -z ${pubkey} ]]; then
+  echo "could not read age public key from /tmp/key.txt"
+  exit 1;
+fi
 # ^ this also checks that the key is present early
+echo "sops-nix will use age public key ${pubkey}"
 
 read -r -p "passphrase for LUKS encryption ~> " passphrase
 
@@ -79,9 +87,9 @@ mkdir -p /mnt/persist/etc/ssh
 ssh-keygen -q -t rsa -b 4096 -C "${hostname}" -N "" -f /mnt/persist/etc/ssh/ssh_host_rsa_key
 ssh-keygen -q -t ed25519 -C "${hostname}" -N "" -f /mnt/persist/etc/ssh/ssh_host_ed25519_key
 
-echo "moving /tmp/key.txt to /etc/sops-nix/key.txt for sops-nix"
-mkdir -p /mnt/persist/var/lib/sops-nix
-mv /tmp/key.txt /mnt/persist/var/lib/sops-nix/
+echo "moving /tmp/key.txt to /persist/etc/sops-nix/key.txt for sops-nix"
+mkdir -p /mnt/persist/etc/sops-nix
+mv /tmp/key.txt /mnt/persist/etc/sops-nix/
 
 echo "running nixos-install"
 time nixos-install --flake ${url} --no-root-password
